### PR TITLE
Implement account presence support in rules

### PR DESCRIPTION
**Pull request by lorenzph**
Hi,

this is the first implementation of account presence changing support. If you find anything which should be changed let me know.

### CODE REVIEW

**Comment by ajalkane** [comment]
Thanks for great work!

By quick testing seems to work really well.

I only glanced through the code, but few comments:

1) In ActionPresenceImpl:.activate, isn't here a theoretical memory leak:

```
if (!_accountManager->isReady(Tp::AccountManager::FeatureCore)) {
    qDebug() << "Rule was activated while Telepathy Account Manager was not ready - will retry as soon as it is ready.";

    _pendingRule = new Rule(rule);
    _pendingRule->setParent(this);

    return;
}
```

If the accountManager is ready in the span of two activate calls, the previous memory allocated for _pendingRule is lost.

2) UI nitpicking: in the SelectionDialog where you select "Online", "Offline" or "Do not change", the selection background color is grey, not blue as it should be.

3) In the Harmattan UI this is called in the pull-down menu "Availability". Why not use that (at least in the UI) instead of "Presence"?

Then I have some questions as a user. Would it be easy to have a restore presence option (similar to restore profile in the profile selection) Ie. when rule that has set presence is not active anymore, it would restore whatever presence user had on before the rule was activated. Use case for me: In home and at work I have computer and want presence off. But when I leave those areas it would be nice if it would turn it back on if I had it on.

Have you considered an "All online" and "All offline" option like Harmattan has? Personally I use gtalk only so it's of no use to me, but on the other hand if I ever add anything else there it would be nice if all would be turned on/off without me readjusting the rules. Not a huge thing though.

Finally, I'm a bit unsure what's the proper way to give credit where credit is due (mainly in the About dialog I guess). Let me know if you have suggestions. Otherwise I'll just try to find some other projects to gleam what's the practice.

**Comment by lorenzph** [comment]
1) You're absolutely right. I will add a check for it (it will get cleaned up once the ActionPresence goes out of scope but that won't happen during the runtime of the daemon).
2) Ok, will change
3) Can change that. The service descriptor files used by the account setup UI used the term presence but as that's not exported to the UI anywhere I'll go with availability.

Regarding the other ideas:

1) Restore presence option: that should be fairly easy to implement and I will add it for the next pull request.
2) I actually thought about adding that functionality after I submitted the pull reques :) The implementation should be pretty straightforward and I'll include it in the next revision.
3) In my projects I add all contributors in the about dialog. If you want to go with that feel free to add me by real name (Philip Lorenz).

I'll try and implement your suggestions and will send an updated pull request as soon as they are ready.

**Comment by ajalkane** [comment]
Thanks.

One more thing... I don't personally have use for it, but I just know people are going to ask that it would be possible to set "Update status message" into the action. You know "I'm at home" type stuff. If its easy, could be nice addition.

I'll go by your suggestion in about dialog, was thinking something like that too.

**Comment by lorenzph** [comment]
Implementation shouldn't be too hard. I'm not too sure how to nicely integrate it in the UI though. I guess there are two alternatives:

1) One textfield at the top of the screen (similar to the built-in availability application setting the status message for all accounts).
2) Availability message on a per account basis. This may be somewhat tricky to present properly in the UI (one could place an icon next to each account but that approach may waste too much horizontal space and may be confusing for some users.

What do you think?

**Comment by ajalkane** [comment]
I think should go with the easy route, one setting for all accounts like in the built-in. As you say the other option would likely confuse some users.

**Comment by lorenzph** [comment]
I have just added the missing features let me know if something is still missing.

**Comment by ajalkane** [comment]
Thanks, it looks excellent!

I have merged your changes to devel branch. Since I don't have time to do any serious work on ProfileMatic for few weeks, I'll probably make a release with your changes in it, because I think this would be quite useful for many people. 

I'll first test it for a bit. If I happen to run into anything minor, I'll try to fix it myself without bothering you. 

There is one thing I raise about the restore previous availability. In the case of restore previous profile, I have made a special case for the default rule: If the rule to activate is the default rule with a profile to set, and the previous rule had "restore" on... then the default rule's profile setting is ignored, and instead the restore previous profile overrides the default rules profile settings. The reasoning is that the default rule is "catch all", and if a default rule has profile setting action then "restore profile" setting makes no sense - the default rule would always override it.

Presence with its multiple accounts is a bit different case, and I'm too weary to think about the full implications. The current code seems to restore the previous presence, and after that apply whatever has been set in the activated profile. Let me know your opinion on the case of activating default rule when previous rule had restore on.

**Comment by lorenzph** [comment]
I wasn't sure myself while implementing the logic behind the restore previous availability functionality. I guess one can argue both ways. In order to stay consistent with the phone profile logic I think it should be changed (I'll update the code and update the pull request to include that behaviour).

**Comment by ajalkane** [comment]
Ok.

While you're at it I noticed a bug which I could not resolve myself with a
quick look:

create a new rule
click on Set account availability

The summary immediately changes to "At least one change" even if you do
nothing on the account page. Basically, you can't get back to the "Don't
change" state after you have visited the availability page.

On Wed, Feb 15, 2012 at 1:56 PM, lorenzph <
reply@reply.github.com

**Comment by lorenzph** [comment]
Fixed in the updated pull request - I forgot to update those functions after I made some changes in the model to support the All online / All offline functionality.

**Comment by ajalkane** [comment]
Seems to work well. Merged to devel, soon proper release.

**Pull request closed without merging**
